name: Cypress Tests

on:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 8080:8080

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start Docker Compose
      run: |
        docker-compose up -d --build

    - name: Wait for application to be ready
      uses: jakejarvis/wait-action@master
      with:
        time: '30s' # Adjust this depending on how long your app takes to start

    - name: Run Cypress tests
      uses: cypress-io/github-action@v2
      with:
        start: echo "Skipping start script because the app is already running via Docker"
        wait-on: 'http://localhost:8080'
        wait-on-timeout: 300
