# This workflow performs a Cypress end-to-end test on the application.
#

name: Cypress Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    # Define the services to start with Docker Compose
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 8080:8080

    steps:

    # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
    - name: Checkout code
      uses: actions/checkout@v4

    # Create the .env files for the frontend, backend, and database from the secrets
    - name: Create .env files
      run: |
        echo "ENVIRONMENT=${{ secrets.ENVIRONMENT }}" > hanoi-frontend/.env
        echo "HANOI_FRONTEND_URL=${{ secrets.HANOI_FRONTEND_URL }}" >> hanoi-frontend/.env
        echo "HANOI_FRONTEND_PORT=${{ secrets.HANOI_FRONTEND_PORT }}" >> hanoi-frontend/.env
        echo "HANOI_BACKEND_URL=${{ secrets.HANOI_BACKEND_URL }}" >> hanoi-frontend/.env
        echo "HANOI_BACKEND_PORT=${{ secrets.HANOI_BACKEND_PORT }}" >> hanoi-frontend/.env
        echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" > hanoi-database/.env
        echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> hanoi-database/.env
        echo "KTOR_ENV=${{ secrets.KTOR_ENV }}" > hanoi-backend/.env
        echo "JWT_DOMAIN=${{ secrets.JWT_DOMAIN }}" >> hanoi-backend/.env
        echo "JWT_AUDIENCE=${{ secrets.JWT_AUDIENCE }}" >> hanoi-backend/.env
        echo "JWT_REALM=${{ secrets.JWT_REALM }}" >> hanoi-backend/.env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> hanoi-backend/.env
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> hanoi-backend/.env
        echo "DATABASE_DRIVER=${{ secrets.DATABASE_DRIVER }}" >> hanoi-backend/.env
        echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> hanoi-backend/.env
        echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> hanoi-backend/.env

    # Ensure Java is installed
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'

    # Ensure Node.js is installed
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.14.0'

    #Ensure Cypress is installed
    - name: Set up Cypress
      run: |
        npm install cypress --save-dev

    # Build the application
    - name: Build with Gradle
      run: |
        ./gradlew build -x detekt
        ./gradlew hanoi-frontend:build
        ./gradlew hanoi-backend:build
        ./gradlew hanoi-backend:buildFatJar

    # Start the application with Docker Compose
    - name: Start Docker Compose
      run: |
        docker-compose up -d --build
    
    # Run the Cypress tests
    - name: Run Cypress tests 
      uses: cypress-io/github-action@v6
      with: 
        start: echo "Skipping start script because the app is already running via Docker"
        wait-on: 'http://localhost:8080'
        wait-on-timeout: 300
