name: Get Detekt Release SHA

on:
  workflow_dispatch:

jobs:
  get-detekt-sha:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: sudo apt-get install -y gh

    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $GITHUB_TOKEN | gh auth login --with-token

    - name: Get Detekt release SHA
      id: get_sha
      run: |
        DETEKT_RELEASE_TAG="v1.23.3"
        gh api graphql --field tagName=$DETEKT_RELEASE_TAG --raw-field query='
          query getReleaseAssetDownloadUrl($tagName: String!) {
            repository(name: "detekt", owner: "detekt") {
              release(tagName: $tagName) {
                tagCommit {
                  oid
                }
              }
            }
          }
        ' > gh_response.json

        DETEKT_RELEASE_SHA=$(jq --raw-output '.data.repository.release.tagCommit.oid' gh_response.json)
        echo "Detekt Release SHA: $DETEKT_RELEASE_SHA"
        echo "::set-output name=sha::$DETEKT_RELEASE_SHA"

    - name: Display Detekt SHA
      run: echo "The Detekt release SHA is ${{ steps.get_sha.outputs.sha }}"
