name: Scan with Detekt

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
     - cron: '32 14 * * 5'
     
  workflow_dispatch:

env:
  DETEKT_RELEASE_TAG: v1.23.3

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Detekt
      run: |
        DETEKT_CLI_VERSION=${{ env.DETEKT_RELEASE_TAG }}
        curl -sSLO https://github.com/detekt/detekt/releases/download/${DETEKT_CLI_VERSION}/detekt-cli-${DETEKT_CLI_VERSION}-all.jar
        echo "::add-path::$(pwd)"
        echo "java -jar $(pwd)/detekt-cli-${DETEKT_CLI_VERSION}-all.jar \$@" > detekt
        chmod +x detekt

    - name: Run Detekt
      continue-on-error: true
      run: |
        ./detekt --input ${{ github.workspace }} --report sarif:${{ github.workspace }}/detekt.sarif.json

    - name: Upload Detekt Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: detekt-report
        path: detekt.sarif.json
